#!/bin/bash
# Stride Validator Auto Installer
while true
do

# Header Include
echo "========================================================================================================================"
curl -s https://raw.githubusercontent.com/giotto-eth/validator/main/header.sh | bash
echo "========================================================================================================================"
# Menu

PS3='Please Select: '
options=(
"Install Node"
"Check Log"
"Check balance"
"Request tokens in discord"
"Create Validator"
"Inject Snapshot 135749 Height 1GB"
"Start with State Sync"
"Add Addrbook"
"Exit")
select opt in "${options[@]}"
do
case $opt in

"Install Node")
echo "============================================================"
echo "Start Setup"
echo "============================================================"
echo "Setup NodeName:"
echo "============================================================"
read NODENAME
echo "============================================================"
echo "Setup WalletName:"
echo "============================================================"
read WALLETNAME
echo export NODENAME=${NODENAME} >> $HOME/.bash_profile
echo export WALLETNAME=${WALLETNAME} >> $HOME/.bash_profile
echo export CHAIN_ID="STRIDE-TESTNET-4" >> $HOME/.bash_profile
source ~/.bash_profile

#APT Update and Upgrade 
sudo apt update && sudo apt upgrade -y
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

#INSTALL GO
rm -r /usr/local/go
rm -r /usr/lib/go-1.13
wget https://golang.org/dl/go1.18.3.linux-amd64.tar.gz; \
rm -rv /usr/local/go; \
tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz && \
rm -v go1.18.3.linux-amd64.tar.gz && \
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile && \
source ~/.bash_profile && \
go version

cd $HOME
rm -rf $HOME/stride $HOME/.stride
#INSTALL
git clone https://github.com/Stride-Labs/stride.git 
cd stride 
git checkout 90859d68d39b53333c303809ee0765add2e59dab
make build
mkdir -p $HOME/go/bin
mv $HOME/stride/build/strided $HOME/go/bin

strided init $NODENAME --chain-id $CHAIN_ID

echo "============================================================"
echo "WRITE DOWN YOUR mnemonic! YOU WONT BE ABLE TO RECOVER YOUR WALLET WITHOUT!"
echo "============================================================"
#WALLET
strided keys add $WALLETNAME

strided tendermint unsafe-reset-all --home $HOME/.stride
rm $HOME/.stride/config/genesis.json
wget -O $HOME/.stride/config/genesis.json "https://raw.githubusercontent.com/Stride-Labs/testnet/main/poolparty/genesis.json"
wget -O $HOME/.stride/config/addrbook.json "https://raw.githubusercontent.com/StakeTake/guidecosmos/main/stride/STRIDE-TESTNET-4/addrbook.json"

SEEDS="d2ec8f968e7977311965c1dbef21647369327a29@seedv2.poolparty.stridenet.co:26656"
PEERS="bf1414a4cbcfcc6c6fc11d1229f5cefcce1faef5@stride-node1.poolparty.stridenet.co:26656"; \
sed -i.bak -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/.stride/config/config.toml


# config pruning
indexer="null"
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="10"

sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/.stride/config/config.toml
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.stride/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.stride/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.stride/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.stride/config/app.toml



tee $HOME/strided.service > /dev/null <<EOF
[Unit]
Description=STRIDE
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which strided) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

sudo mv $HOME/strided.service /etc/systemd/system/

# start service
sudo systemctl daemon-reload
sudo systemctl enable strided
sudo systemctl restart strided

break
;;

"Check Log")

journalctl -u strided -f -o cat

break
;;


"Check balance")
strided q bank balances $(strided keys show $WALLETNAME -a --bech acc)
break
;;

"Create Stride Validator")
strided tx staking create-validator \
  --amount 1000000ustrd \
  --from $WALLETNAME \
  --commission-max-change-rate "0.05" \
  --commission-max-rate "0.20" \
  --commission-rate "0.05" \
  --min-self-delegation "1" \
  --pubkey $(strided tendermint show-validator) \
  --moniker $NODENAME \
  --chain-id $CHAIN_ID \
  --gas 300000 \
  -y
break
;;

"Token Request in Discord")
echo "=========================================================================================================================================================================================-"
echo "| If you want to receive tokens you need to go to the Discord Server: https://discord.gg/j2pzfHwq and request tokens in the validator channel and use $faucet-stride:strideREPLACEYOURID"|
echo "=========================================================================================================================================================================================-"

break
;;

"Inject Snapshot 135749 height 1gb")
sudo systemctl stop strided
strided tendermint unsafe-reset-all --home $HOME/.stride --keep-addr-book
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="10"
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.stride/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.stride/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.stride/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.stride/config/app.toml
cd
rm -rf ~/.stride/data; \
wget -O - http://snap.stake-take.com:8000/stride.tar.gz | tar xf -
mv $HOME/root/.stride/data $HOME/.stride
rm -rf $HOME/root
sudo systemctl restart strided && journalctl -u strided -f -o cat

break
;;

"Start with state sync")
sudo systemctl stop strided
strided tendermint unsafe-reset-all --home $HOME/.stride
SEEDS=""
PEERS="6d3d7df642fd0cdf0c4b74c499cf4d5937a29d2b@23.88.100.175:26656,bf1414a4cbcfcc6c6fc11d1229f5cefcce1faef5@stride-node1.poolparty.stridenet.co:26656"; \
sed -i.bak -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/.stride/config/config.toml
SNAP_RPC="http://stride.stake-take.com:26657"
LATEST_HEIGHT=$(curl -s $SNAP_RPC/block | jq -r .result.block.header.height); \
BLOCK_HEIGHT=$((LATEST_HEIGHT - 2000)); \
TRUST_HASH=$(curl -s "$SNAP_RPC/block?height=$BLOCK_HEIGHT" | jq -r .result.block_id.hash)
echo $LATEST_HEIGHT $BLOCK_HEIGHT $TRUST_HASH
sed -i.bak -E "s|^(enable[[:space:]]+=[[:space:]]+).*$|\1true| ; \
s|^(rpc_servers[[:space:]]+=[[:space:]]+).*$|\1\"$SNAP_RPC,$SNAP_RPC\"| ; \
s|^(trust_height[[:space:]]+=[[:space:]]+).*$|\1$BLOCK_HEIGHT| ; \
s|^(trust_hash[[:space:]]+=[[:space:]]+).*$|\1\"$TRUST_HASH\"| ; \
s|^(seeds[[:space:]]+=[[:space:]]+).*$|\1\"\"|" $HOME/.stride/config/config.toml
wget -O $HOME/.stride/config/addrbook.json "https://raw.githubusercontent.com/StakeTake/guidecosmos/main/stride/STRIDE-TESTNET-4/addrbook.json"
sudo systemctl restart strided && journalctl -u strided -f -o cat

break
;;

"Add Addrbook")
sudo systemctl stop strided
rm $HOME/.stride/config/addrbook.json
wget -O $HOME/.stride/config/addrbook.json "https://raw.githubusercontent.com/StakeTake/guidecosmos/main/stride/STRIDE-TESTNET-4/addrbook.json"
sudo systemctl restart strided && journalctl -u strided -f -o cat

break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
